name: functional-tests

on:
  push:
    branches:
      - main
    paths:
      - '**/*.py'
  workflow_dispatch:

jobs:
  functional-tests:
    strategy:
      matrix:
        platform:
          - release_for: linux-amd64
          - release_for: darwin-amd64
          - release_for: windows-amd64
    name: Test functionality on ${{ matrix.platform.release_for }}
    runs-on:
      - thevickypedia-default
      - ${{ matrix.platform.release_for }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        if: matrix.platform.release_for != 'darwin-amd64'
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          export PYTHONPATH="$(pwd):$PYTHONPATH"
          python -m pip install .
        shell: bash

      - name: Run functional tests
        run: python functional.py
        working-directory: tests
        shell: bash
